import { StyleSheet, Platform } from 'react-native';

export const styles = StyleSheet.create({
  // Root App Container (Responsive: Mobile centered on Desktop)
  appBackground: {
    flex: 1,
    backgroundColor: '#090d16',
    alignItems: 'center',
    justifyContent: 'center',
  },
  appContainer: {
    flex: 1,
    width: '100%',
    maxWidth: 480,
    backgroundColor: '#f8fafc',
    overflow: 'hidden',
    position: 'relative',
    ...(Platform.OS === 'web' ? {
      boxShadow: '0 25px 60px -12px rgba(0, 0, 0, 0.65)',
      height: '100vh',
      maxHeight: '100vh',
    } : {}),
  },

  // Login Screen with Blurred Background & RSJ Branding
  loginBackground: {
    flex: 1,
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
  },
  loginBgOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(15, 23, 42, 0.62)',
    ...(Platform.OS === 'web' ? {
      background: 'linear-gradient(180deg, rgba(15, 23, 42, 0.55) 0%, rgba(2, 132, 199, 0.35) 50%, rgba(15, 23, 42, 0.75) 100%)',
    } : {}),
  },
  watermarkLogo: {
    position: 'absolute',
    width: 320,
    height: 320,
    opacity: 0.16,
    alignSelf: 'center',
    top: '18%',
  },
  loginCardGlass: {
    width: '92%',
    maxWidth: 410,
    backgroundColor: 'rgba(255, 255, 255, 0.88)',
    borderRadius: 24,
    padding: 22,
    borderWidth: 1.5,
    borderColor: 'rgba(255, 255, 255, 0.85)',
    zIndex: 10,
    ...(Platform.OS === 'web' ? {
      backdropFilter: 'blur(24px)',
      boxShadow: '0 20px 45px -10px rgba(0, 0, 0, 0.45)',
    } : { elevation: 8 }),
  },
  logoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
  },
  logoBadge: {
    width: 54,
    height: 54,
    borderRadius: 16,
    backgroundColor: '#ffffff',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
    borderWidth: 1.5,
    borderColor: '#e2e8f0',
    overflow: 'hidden',
    ...(Platform.OS === 'web' ? {
      boxShadow: '0 4px 10px rgba(0, 0, 0, 0.08)',
    } : {}),
  },
  logoImg: {
    width: 44,
    height: 44,
    resizeMode: 'contain',
  },
  logoTitle: {
    fontSize: 19,
    fontWeight: '900',
    color: '#0f172a',
    letterSpacing: 0.5,
  },
  logoSub: {
    fontSize: 10.5,
    fontWeight: '800',
    color: '#0284c7',
    letterSpacing: 0.8,
  },
  tagline: {
    color: '#475569',
    fontSize: 11.5,
    marginBottom: 16,
    lineHeight: 16,
  },
  loginTitle: {
    color: '#0f172a',
    fontSize: 17,
    fontWeight: '800',
    marginBottom: 12,
  },
  inputWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    height: 46,
    borderWidth: 1.5,
    borderColor: '#cbd5e1',
    borderRadius: 12,
    marginBottom: 10,
    paddingHorizontal: 12,
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
  },
  inputIcon: {
    fontSize: 16,
    marginRight: 8,
  },
  input: {
    flex: 1,
    color: '#0f172a',
    fontSize: 13.5,
    outlineStyle: 'none',
  },
  eyeButton: {
    padding: 6,
  },
  loginButton: {
    height: 46,
    backgroundColor: '#0284c7',
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 4,
    ...(Platform.OS === 'web' ? {
      boxShadow: '0 6px 16px rgba(2, 132, 199, 0.38)',
    } : {}),
  },
  loginButtonText: {
    color: '#ffffff',
    fontSize: 14.5,
    fontWeight: '800',
    letterSpacing: 0.5,
  },
  quickLoginSection: {
    marginTop: 16,
    paddingTop: 14,
    borderTopWidth: 1,
    borderTopColor: '#e2e8f0',
  },
  quickLoginTitle: {
    fontSize: 10.5,
    fontWeight: '800',
    color: '#64748b',
    textTransform: 'uppercase',
    marginBottom: 8,
    textAlign: 'center',
  },
  quickLoginBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    borderWidth: 1,
    borderColor: '#e2e8f0',
    borderRadius: 10,
    paddingVertical: 7,
    paddingHorizontal: 10,
    marginBottom: 6,
  },

  // App Header
  header: {
    height: 60,
    backgroundColor: '#ffffff',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#e2e8f0',
    zIndex: 20,
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  menuButton: {
    paddingVertical: 7,
    paddingHorizontal: 10,
    backgroundColor: '#f1f5f9',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  menuText: {
    fontWeight: '700',
    color: '#0f172a',
    fontSize: 13,
  },
  backButton: {
    paddingVertical: 7,
    paddingHorizontal: 10,
    backgroundColor: '#e0f2fe',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#bae6fd',
  },
  backText: {
    fontWeight: '700',
    color: '#0284c7',
    fontSize: 12,
  },
  headerTitle: {
    fontSize: 14.5,
    fontWeight: '800',
    color: '#0f172a',
  },
  notification: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: '#f1f5f9',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },

  // Scroll and Page
  scroll: {
    flex: 1,
  },
  page: {
    padding: 16,
    paddingBottom: 36,
  },

  // Dashboard Welcome Banner
  welcome: {
    backgroundColor: '#0284c7',
    borderRadius: 20,
    padding: 18,
    marginBottom: 16,
    overflow: 'hidden',
    position: 'relative',
    ...(Platform.OS === 'web' ? {
      boxShadow: '0 10px 20px -5px rgba(2, 132, 199, 0.35)',
    } : {}),
  },
  welcomeSmall: {
    color: '#bae6fd',
    fontSize: 12,
    fontWeight: '600',
  },
  welcomeName: {
    color: '#ffffff',
    fontSize: 19,
    fontWeight: '900',
    marginTop: 2,
  },
  badge: {
    alignSelf: 'flex-start',
    backgroundColor: 'rgba(255,255,255,0.22)',
    paddingHorizontal: 10,
    paddingVertical: 3,
    borderRadius: 12,
    marginVertical: 6,
  },
  badgeText: {
    color: '#ffffff',
    fontSize: 11,
    fontWeight: '700',
  },
  timeRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 10,
    borderTopWidth: 1,
    borderTopColor: 'rgba(255,255,255,0.2)',
    paddingTop: 10,
  },
  date: {
    color: '#ffffff',
    fontSize: 12,
    fontWeight: '600',
  },
  clock: {
    color: '#ffffff',
    backgroundColor: 'rgba(0,0,0,0.25)',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 8,
    fontFamily: 'monospace',
    fontWeight: '800',
    fontSize: 13,
  },

  // Daily Status Banner on Dashboard
  todayStatusCard: {
    backgroundColor: '#ffffff',
    borderRadius: 16,
    padding: 14,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },

  // Action Cards Grid
  cards: {
    gap: 12,
  },
  actionCard: {
    borderRadius: 18,
    padding: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    ...(Platform.OS === 'web' ? {
      boxShadow: '0 4px 12px rgba(0, 0, 0, 0.08)',
    } : { elevation: 3 }),
  },
  cardTitle: {
    color: '#ffffff',
    fontSize: 15,
    fontWeight: '800',
    marginBottom: 3,
  },
  cardDesc: {
    color: 'rgba(255,255,255,0.92)',
    fontSize: 11.5,
    lineHeight: 15,
  },
  cardArrow: {
    fontSize: 20,
    marginLeft: 10,
  },

  // Section Styles
  section: {
    backgroundColor: '#ffffff',
    borderRadius: 16,
    padding: 16,
    marginTop: 16,
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  sectionTitle: {
    fontSize: 14,
    fontWeight: '800',
    color: '#0f172a',
    marginBottom: 10,
  },
  day: {
    width: 44,
    paddingVertical: 8,
    borderRadius: 10,
    backgroundColor: '#f8fafc',
    borderWidth: 1,
    borderColor: '#e2e8f0',
    alignItems: 'center',
    marginRight: 8,
  },
  today: {
    borderColor: '#0284c7',
    backgroundColor: '#e0f2fe',
    borderWidth: 1.5,
  },
  dayNumber: {
    fontSize: 12,
    fontWeight: '800',
    color: '#475569',
  },
  shift: {
    width: 24,
    height: 24,
    borderRadius: 6,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 6,
  },
  shiftText: {
    color: '#ffffff',
    fontSize: 11,
    fontWeight: '800',
  },

  // Attendance Screen
  banner: {
    backgroundColor: '#ecfdf5',
    borderLeftWidth: 4,
    borderLeftColor: '#10b981',
    padding: 14,
    borderRadius: 10,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: '#a7f3d0',
  },
  bannerDording: {
    backgroundColor: '#fffbeb',
    borderLeftColor: '#f59e0b',
    borderColor: '#fde68a',
  },
  bannerTitle: {
    color: '#065f46',
    fontWeight: '800',
    fontSize: 13.5,
  },
  bannerSub: {
    color: '#047857',
    fontSize: 11.5,
    marginTop: 3,
  },
  map: {
    backgroundColor: '#f1f5f9',
    borderRadius: 16,
    padding: 16,
    alignItems: 'center',
    marginBottom: 14,
    borderWidth: 1,
    borderColor: '#cbd5e1',
  },
  mapText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#1e293b',
    marginTop: 4,
  },
  geo: {
    backgroundColor: '#ecfdf5',
    color: '#059669',
    borderWidth: 1,
    borderColor: '#10b981',
    paddingHorizontal: 10,
    paddingVertical: 3,
    borderRadius: 8,
    fontSize: 11,
    fontWeight: '800',
    marginTop: 6,
  },
  clockCard: {
    backgroundColor: '#ffffff',
    borderRadius: 16,
    padding: 16,
    alignItems: 'center',
    marginBottom: 14,
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  bigClock: {
    fontSize: 32,
    fontWeight: '900',
    color: '#0f172a',
    fontFamily: 'monospace',
    letterSpacing: 1,
  },
  muted: {
    fontSize: 12,
    color: '#64748b',
    marginTop: 2,
    fontWeight: '600',
  },
  actionButton: {
    height: 48,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 12,
  },
  actionText: {
    color: '#ffffff',
    fontSize: 13.5,
    fontWeight: '800',
  },
  detailText: {
    fontSize: 12.5,
    color: '#475569',
    marginVertical: 4,
  },
  label: {
    fontSize: 12,
    fontWeight: '700',
    color: '#334155',
    marginBottom: 5,
  },
  primaryButton: {
    height: 46,
    backgroundColor: '#0284c7',
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 12,
  },

  // Drawer styles (fixed width 285px, responsive, auto-close)
  drawerBackdrop: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(15, 23, 42, 0.65)',
    zIndex: 100,
  },
  drawer: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: 285,
    height: '100%',
    backgroundColor: '#0f172a',
    zIndex: 110,
    padding: 20,
    display: 'flex',
    flexDirection: 'column',
    borderRightWidth: 1,
    borderRightColor: '#334155',
    ...(Platform.OS === 'web' ? {
      boxShadow: '10px 0 25px rgba(0, 0, 0, 0.5)',
    } : {}),
  },
  drawerHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 10,
    marginBottom: 16,
    paddingBottom: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#1e293b',
  },
  drawerLogo: {
    color: '#ffffff',
    fontSize: 15,
    fontWeight: '900',
  },
  drawerCloseBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#1e293b',
    justifyContent: 'center',
    alignItems: 'center',
  },
  drawerUser: {
    backgroundColor: 'rgba(255,255,255,0.06)',
    padding: 12,
    borderRadius: 12,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
  },
  drawerName: {
    color: '#ffffff',
    fontSize: 13.5,
    fontWeight: '800',
  },
  drawerRole: {
    color: '#38bdf8',
    fontSize: 11,
    fontWeight: '600',
    marginTop: 3,
  },
  navItem: {
    paddingVertical: 12,
    paddingHorizontal: 12,
    borderRadius: 10,
    marginBottom: 4,
  },
  navItemActive: {
    backgroundColor: '#0284c7',
  },
  navText: {
    color: '#cbd5e1',
    fontSize: 13.5,
    fontWeight: '700',
  },
  navTextActive: {
    color: '#ffffff',
  },
  logout: {
    backgroundColor: 'rgba(239, 68, 68, 0.15)',
    borderWidth: 1,
    borderColor: 'rgba(239, 68, 68, 0.3)',
    padding: 12,
    borderRadius: 12,
    alignItems: 'center',
    marginBottom: 20,
  },
  logoutText: {
    color: '#f87171',
    fontWeight: '800',
    fontSize: 13,
  },

  // Face Recognition Modal
  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(15, 23, 42, 0.85)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 16,
  },
  modal: {
    width: '100%',
    maxWidth: 380,
    backgroundColor: '#0f172a',
    borderRadius: 24,
    padding: 20,
    borderWidth: 1,
    borderColor: '#334155',
    ...(Platform.OS === 'web' ? {
      boxShadow: '0 25px 50px -12px rgba(0, 0, 0, 0.5)',
    } : {}),
  },
  modalTitle: {
    fontSize: 15,
    fontWeight: '800',
    color: '#f8fafc',
  },
  camera: {
    height: 220,
    backgroundColor: '#020617',
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
    overflow: 'hidden',
  },
  cameraText: {
    color: '#38bdf8',
    fontSize: 12,
    fontWeight: '800',
    marginTop: 6,
    textAlign: 'center',
  },
  stamp: {
    color: '#ffffff',
    fontSize: 10.5,
    fontWeight: '700',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 6,
  },
});